---
# model_name: gpt-3.5-turbo
model_name: gpt-4
num_topics: [10]  # number of topics to put into the conversation
num_test_samples: 1 # number of test samples in each test case
question_dist: 3  # will ask what is the topic discussed every # topics eg. 1st, 4th
# run_models: False   # if set to False, only outputs token size
run_models: True
# generate_conversations: True # if set to False, will ask for a path to conversations to form the prompt
generate_conversations: True

